// Generated by Framer (ba156f5)

import { addFonts, addPropertyControls, ControlType, cx, Instance, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS, withFX } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import XLogo from "https://framerusercontent.com/modules/oMiuMYAdxzz5yk7pBqrm/j2eV5wGWikO42mvtQ2hM/Xx_sbLkzD.js";
const MotionDivWithFX = withFX(motion.div);

const serializationHash = "framer-b9UvX"

const variantClassNames = {kGevhqcJt: "framer-v-jmrajk"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const animation = {opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: -50, y: 0}

const transition1 = {damping: 25, delay: 0.45, mass: 1, stiffness: 127, type: "spring"}

const animation1 = {opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition1, x: -50, y: 0}

const transition2 = {bounce: 0.2, delay: 0, duration: 0.4, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({height, icon, id, text, width, ...props}) => { return {...props, D9G1UslsE: text ?? props.D9G1UslsE ?? "Video & Motion Graphics", fb_00tkWM: icon ?? props.fb_00tkWM ?? XLogo} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;icon?: React.ComponentType<any> | undefined;text?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, fb_00tkWM, D9G1UslsE, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "kGevhqcJt", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition2}><MotionDivWithFX {...restProps} {...gestureHandlers} __framer__animate={{transition: transition1}} __framer__animateOnce __framer__enter={animation} __framer__exit={animation1} __framer__styleAppearEffectEnabled __framer__threshold={0} __perspectiveFX={false} __smartComponentFX __targetOpacity={1} className={cx(scopingClassNames, "framer-jmrajk", className, classNames)} data-framer-name={"primary"} layoutDependency={layoutDependency} layoutId={"kGevhqcJt"} ref={refBinding} style={{backgroundColor: "var(--token-c3117f11-2133-438b-a938-79a439f8c3a4, rgb(95, 59, 249))", borderBottomLeftRadius: 78, borderBottomRightRadius: 78, borderTopLeftRadius: 78, borderTopRightRadius: 78, ...style}}><Instance animated className={"framer-1615j1x"} Component={fb_00tkWM} layoutDependency={layoutDependency} layoutId={"DggYPulyA"} style={{"--1m6trwb": 0.2, "--21h8s6": "rgb(255, 255, 255)", "--pgex8v": 1.5}}/><RichText __fromCanvasComponent children={<React.Fragment><motion.p style={{"--framer-font-size": "15px", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1.5em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"}}>Video &amp; Motion Graphics</motion.p></React.Fragment>} className={"framer-2mglhp"} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"Qdd6tSuIB"} style={{"--extracted-r6o4lv": "rgb(255, 255, 255)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"}} text={D9G1UslsE} verticalAlignment={"top"} withExternalLayout/></MotionDivWithFX></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-b9UvX.framer-1ri0uy6, .framer-b9UvX .framer-1ri0uy6 { display: block; }", ".framer-b9UvX.framer-jmrajk { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 14px 16px 14px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-b9UvX .framer-1615j1x { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }", ".framer-b9UvX .framer-2mglhp { flex: none; height: auto; position: relative; white-space: pre; width: auto; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 51
 * @framerIntrinsicWidth 231
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"fb_00tkWM":"icon","D9G1UslsE":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["omX0gWFPqDwhaiWwf6ab"]
 */
const FramerLBOVeheKZ: React.ComponentType<Props> = withCSS(Component, css, "framer-b9UvX") as typeof Component;
export default FramerLBOVeheKZ;

FramerLBOVeheKZ.displayName = "small badge card";

FramerLBOVeheKZ.defaultProps = {height: 51, width: 231};

addPropertyControls(FramerLBOVeheKZ, {fb_00tkWM: {defaultValue: {identifier: "module:oMiuMYAdxzz5yk7pBqrm/j2eV5wGWikO42mvtQ2hM/Xx_sbLkzD.js:default", moduleId: "oMiuMYAdxzz5yk7pBqrm"}, setModuleId: "omX0gWFPqDwhaiWwf6ab", title: "Icon", type: ControlType.VectorSetItem}, D9G1UslsE: {defaultValue: "Video & Motion Graphics", displayTextArea: false, title: "text", type: ControlType.String}} as any)

addFonts(FramerLBOVeheKZ, [{explicitInter: true, fonts: [{family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400"}]}], {supportsExplicitInterCodegen: true})