// Generated by Framer (d65dc2b)

import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const cycleOrder = ["CPbzKAr6L", "JrHCHZ8vy"];

const serializationHash = "framer-HKKkw"

const variantClassNames = {CPbzKAr6L: "framer-v-zh8s9o", JrHCHZ8vy: "framer-v-12pev7f"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 20, delay: 0, mass: 1, stiffness: 300, type: "spring"}

const radiusForCorner = (value, cornerIndex) => {
    if (typeof value === "number" && Number.isFinite(value)) return Math.max(0, value) + "px";
    if (typeof value !== "string" || typeof cornerIndex !== "number") return undefined;
    const segments = value.split(" ");
    return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};


const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const humanReadableVariantMap = {Close: "JrHCHZ8vy", Hamburger: "CPbzKAr6L"}

const getProps = ({height, id, radius, width, ...props}) => { return {...props, d2WdKj7yR: radius ?? props.d2WdKj7yR, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "CPbzKAr6L"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap;radius?: number; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, d2WdKj7yR, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "CPbzKAr6L", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)

const onTap1jed072 = activeVariantCallback(async (...args) => {
setGestureState({isPressed: false})
setVariant("JrHCHZ8vy")
})

const onTap13q1h6c = activeVariantCallback(async (...args) => {
setGestureState({isPressed: false})
setVariant("CPbzKAr6L")
})

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-zh8s9o", className, classNames)} data-framer-name={"Hamburger"} data-highlight layoutDependency={layoutDependency} layoutId={"CPbzKAr6L"} onTap={onTap1jed072} ref={refBinding} style={{...style}} {...addPropertyOverrides({JrHCHZ8vy: {"data-framer-name": "Close", onTap: onTap13q1h6c}}, baseVariant, gestureVariant)}><motion.div className={"framer-bciays"} layoutDependency={layoutDependency} layoutId={"D8g0i2TPu"} style={{backgroundColor: "var(--token-67527bae-cc15-4839-8636-c9b28351e4d7, rgb(15, 63, 124))", borderBottomLeftRadius: radiusForCorner(d2WdKj7yR, 3), borderBottomRightRadius: radiusForCorner(d2WdKj7yR, 2), borderTopLeftRadius: radiusForCorner(d2WdKj7yR, 0), borderTopRightRadius: radiusForCorner(d2WdKj7yR, 1), rotate: 0}} variants={{JrHCHZ8vy: {backgroundColor: "var(--token-0c62d1bb-1ac3-4cd6-8f0f-8ee3950e02c0, rgb(255, 0, 0))", rotate: 45}}}/><motion.div className={"framer-8e3nfd"} layoutDependency={layoutDependency} layoutId={"S4N9rAXvt"} style={{backgroundColor: "var(--token-67527bae-cc15-4839-8636-c9b28351e4d7, rgb(15, 63, 124))", borderBottomLeftRadius: radiusForCorner(d2WdKj7yR, 3), borderBottomRightRadius: radiusForCorner(d2WdKj7yR, 2), borderTopLeftRadius: radiusForCorner(d2WdKj7yR, 0), borderTopRightRadius: radiusForCorner(d2WdKj7yR, 1), rotate: 0}} variants={{JrHCHZ8vy: {backgroundColor: "var(--token-0c62d1bb-1ac3-4cd6-8f0f-8ee3950e02c0, rgb(255, 0, 0))", rotate: -45}}}/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-HKKkw.framer-nebkpz, .framer-HKKkw .framer-nebkpz { display: block; }", ".framer-HKKkw.framer-zh8s9o { cursor: pointer; height: 30px; overflow: hidden; position: relative; width: 30px; }", ".framer-HKKkw .framer-bciays { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: visible; position: absolute; top: 10px; width: 20px; }", ".framer-HKKkw .framer-8e3nfd { bottom: 10px; flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: visible; position: absolute; width: 20px; }", ".framer-HKKkw.framer-v-12pev7f.framer-zh8s9o { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 30px); }", ".framer-HKKkw.framer-v-12pev7f .framer-bciays { top: calc(50.00000000000002% - 2px / 2); }", ".framer-HKKkw.framer-v-12pev7f .framer-8e3nfd { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 30
 * @framerIntrinsicWidth 30
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"JrHCHZ8vy":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"d2WdKj7yR":"radius"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerMmHwaI6bc: React.ComponentType<Props> = withCSS(Component, css, "framer-HKKkw") as typeof Component;
export default FramerMmHwaI6bc;

FramerMmHwaI6bc.displayName = "Menu Icon";

FramerMmHwaI6bc.defaultProps = {height: 30, width: 30};

addPropertyControls(FramerMmHwaI6bc, {variant: {options: ["CPbzKAr6L", "JrHCHZ8vy"], optionTitles: ["Hamburger", "Close"], title: "Variant", type: ControlType.Enum}, d2WdKj7yR: {defaultValue: 0, displayStepper: true, max: 1, min: 0, title: "Radius", type: ControlType.Number}} as any)

addFonts(FramerMmHwaI6bc, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})