// Generated by Framer (06534cb)

import { addFonts, addPropertyControls, ControlType, cx, CycleVariantState, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useOnVariantChange, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const cycleOrder = ["ZlLcJoaKS", "lgehuRi4E"];

const serializationHash = "framer-qKG9f"

const variantClassNames = {lgehuRi4E: "framer-v-greys1", ZlLcJoaKS: "framer-v-1vb5qbg"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {duration: 0, type: "tween"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const humanReadableVariantMap = {off: "lgehuRi4E", on: "ZlLcJoaKS"}

const getProps = ({colorOff, colorOn, height, id, width, ...props}) => { return {...props, tV6RQgjy4: colorOn ?? props.tV6RQgjy4 ?? "var(--token-824b0275-9b90-4fdc-a563-7ec722d766de, rgb(213, 192, 43))", variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "ZlLcJoaKS", ZyC20jIX2: colorOff ?? props.ZyC20jIX2 ?? "rgba(133, 222, 255, 0.5)"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap;colorOn?: string;colorOff?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const {style, className, layoutId, variant, tV6RQgjy4, ZyC20jIX2, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "ZlLcJoaKS", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)

const onAppear1f7mxo0 = activeVariantCallback(async (...args) => {
await delay(() => setVariant("lgehuRi4E"), 1000)
})

const onAppearxsl9u9 = activeVariantCallback(async (...args) => {
await delay(() => setVariant("ZlLcJoaKS"), 1000)
})

useOnVariantChange(baseVariant, {default: onAppear1f7mxo0, lgehuRi4E: onAppearxsl9u9})

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-1vb5qbg", className, classNames)} data-framer-name={"on"} data-highlight layoutDependency={layoutDependency} layoutId={"ZlLcJoaKS"} ref={refBinding} style={{backgroundColor: tV6RQgjy4, borderBottomLeftRadius: 84, borderBottomRightRadius: 84, borderTopLeftRadius: 84, borderTopRightRadius: 84, boxShadow: "0px 0px 14px 1px rgb(189, 189, 189)", ...style}} variants={{lgehuRi4E: {backgroundColor: ZyC20jIX2, boxShadow: "none"}}} {...addPropertyOverrides({lgehuRi4E: {"data-framer-name": "off"}}, baseVariant, gestureVariant)}/></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-qKG9f.framer-1hwk5rl, .framer-qKG9f .framer-1hwk5rl { display: block; }", ".framer-qKG9f.framer-1vb5qbg { height: 5px; overflow: hidden; position: relative; width: 5px; will-change: var(--framer-will-change-override, transform); }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 5
 * @framerIntrinsicWidth 5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"lgehuRi4E":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"tV6RQgjy4":"colorOn","ZyC20jIX2":"colorOff"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FrameryOOmeTSWl: React.ComponentType<Props> = withCSS(Component, css, "framer-qKG9f") as typeof Component;
export default FrameryOOmeTSWl;

FrameryOOmeTSWl.displayName = "Elements / on&off";

FrameryOOmeTSWl.defaultProps = {height: 5, width: 5};

addPropertyControls(FrameryOOmeTSWl, {variant: {options: ["ZlLcJoaKS", "lgehuRi4E"], optionTitles: ["on", "off"], title: "Variant", type: ControlType.Enum}, tV6RQgjy4: {defaultValue: "var(--token-824b0275-9b90-4fdc-a563-7ec722d766de, rgb(213, 192, 43)) /* {\"name\":\"Primary Color Yellow\"} */", title: "color/on", type: ControlType.Color}, ZyC20jIX2: {defaultValue: "rgba(133, 222, 255, 0.5)", title: "color/off", type: ControlType.Color}} as any)

addFonts(FrameryOOmeTSWl, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})