// Generated by Framer (ba156f5)

import { addFonts, addPropertyControls, ControlType, cx, Instance, Link, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import XLogo from "https://framerusercontent.com/modules/oMiuMYAdxzz5yk7pBqrm/j2eV5wGWikO42mvtQ2hM/Xx_sbLkzD.js";

const enabledGestures = {AnDrkir1_: {hover: true}};

const serializationHash = "framer-4zJgd"

const variantClassNames = {AnDrkir1_: "framer-v-ir3zuj"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {bounce: 0.2, delay: 0, duration: 0.4, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({height, icon, id, link, width, ...props}) => { return {...props, lPiu_Mix0: icon ?? props.lPiu_Mix0 ?? XLogo, YdTA2k7Lp: link ?? props.YdTA2k7Lp} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;icon?: React.ComponentType<any> | undefined;link?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, lPiu_Mix0, YdTA2k7Lp, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "AnDrkir1_", enabledGestures, ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><Link href={YdTA2k7Lp} motionChild nodeId={"AnDrkir1_"} openInNewTab scopeId={"xM7nbLS6Z"}><motion.a {...restProps} {...gestureHandlers} className={`${cx(scopingClassNames, "framer-ir3zuj", className, classNames)} framer-14ihfls`} data-framer-name={"primary"} layoutDependency={layoutDependency} layoutId={"AnDrkir1_"} ref={refBinding} style={{borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, ...style}} {...addPropertyOverrides({"AnDrkir1_-hover": {"data-framer-name": undefined}}, baseVariant, gestureVariant)}><Instance animated className={"framer-jzkyzy"} Component={lPiu_Mix0} layoutDependency={layoutDependency} layoutId={"UeGJUHjZg"} style={{"--1m6trwb": 0.2, "--21h8s6": "var(--token-67527bae-cc15-4839-8636-c9b28351e4d7, rgb(255, 255, 255))", "--pgex8v": 1.5}}/></motion.a></Link></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-4zJgd.framer-14ihfls, .framer-4zJgd .framer-14ihfls { display: block; }", ".framer-4zJgd.framer-ir3zuj { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-4zJgd .framer-jzkyzy { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 40
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"xPe57n0dv":{"layout":["auto","auto"]}}}
 * @framerVariables {"lPiu_Mix0":"icon","YdTA2k7Lp":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["omX0gWFPqDwhaiWwf6ab"]
 */
const FramerxM7nbLS6Z: React.ComponentType<Props> = withCSS(Component, css, "framer-4zJgd") as typeof Component;
export default FramerxM7nbLS6Z;

FramerxM7nbLS6Z.displayName = "Elements/social media";

FramerxM7nbLS6Z.defaultProps = {height: 40, width: 40};

addPropertyControls(FramerxM7nbLS6Z, {lPiu_Mix0: {defaultValue: {identifier: "module:oMiuMYAdxzz5yk7pBqrm/j2eV5wGWikO42mvtQ2hM/Xx_sbLkzD.js:default", moduleId: "oMiuMYAdxzz5yk7pBqrm"}, setModuleId: "omX0gWFPqDwhaiWwf6ab", title: "Icon", type: ControlType.VectorSetItem}, YdTA2k7Lp: {title: "Link", type: ControlType.Link}} as any)

addFonts(FramerxM7nbLS6Z, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})